name: stegocaps
version: '0.1' 
summary: a collection of simple text-based steganography tools
description: |
  STegOcaPs is a collection of simple text-based steganography implementations 
  based around hiding the secret text in a cover text by manipulating the 
  capitalization of the cover text letters.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  stegocaps:
    # See 'snapcraft plugins'
    plugin: python
      python-version: python2

apps:
  stegocaps:
    command: stegocaps
